### ISSUE TITLE
model_config.json文件

### ISSUE THREAD

**Issue by guofengming11** [zhiyou720/nlp_preprocess#1]
请问可以提供一下model_config.json这个文件吗

**Comment by zhiyou720** [comment]
有两个模型，一个分段模型，一个标点模型。

**Comment by zhiyou720** [comment]
> 请问可以提供一下model_config.json这个文件吗

有两个模型，一个分段模型，一个标点模型。

**Comment by guofengming11** [comment]
我是想做无标点文本自动添加标点

**Comment by zhiyou720** [comment]
> 我是想做无标点文本自动添加标点

那我把模型上传一下吧。

**Comment by guofengming11** [comment]
多谢多谢

**Comment by zhiyou720** [comment]
> 多谢多谢

客气了 给个star就好

**Comment by zhiyou720** [comment]
> 多谢多谢

上传到网盘了，见readme
