### ISSUE TITLE
添加标点符号的时候最前面总是有一个 “ 但是后面却没有与之匹配的 “，这是咋回事呢

### ISSUE THREAD

**Issue by HandsLing** [zhiyou720/nlp_preprocess#2]
请输入要断句的文字：
嗯你刚之前参加了一个投资理财今天发现是骗局我爸投资理财被骗了六万多六万多全骗没了啊已经报警了
“嗯！你刚之前参加了一个投资理财，今天发现是骗局，我爸投资理财被骗了，六万多六万多，全骗没了啊，已经报警了。
请输入要断句的文字：
要多照顾她她有高血压
“要多照顾她，她有高血压。
这是其中两条结果，但是也不是所有的都会出现这种情况

**Comment by HandsLing** [comment]
还有就是可以给出训练代码以及训练样本的示例吗？

**Comment by zhiyou720** [comment]
> 请输入要断句的文字：
> 嗯你刚之前参加了一个投资理财今天发现是骗局我爸投资理财被骗了六万多六万多全骗没了啊已经报警了
> “嗯！你刚之前参加了一个投资理财，今天发现是骗局，我爸投资理财被骗了，六万多六万多，全骗没了啊，已经报警了。
> 请输入要断句的文字：
> 要多照顾她她有高血压
> “要多照顾她，她有高血压。
> 这是其中两条结果，但是也不是所有的都会出现这种情况

像这种左右匹配的训练的效果都不太好，可以不预测这种标点。

**Comment by zhiyou720** [comment]
> 还有就是可以给出训练代码以及训练样本的示例吗？

训练代码即将整合进来
